// Vue/src/components/cabecalho/Header.vue
<template>
  <header id="cabecalho">
    <CabecalhoPrincipal :saldo="totais.total"/>
    <CabecalhoConteudo :totais="totais"/>
  </header>
</template>

<script>
import CabecalhoPrincipal from "./CabecalhoPrincipal";
import CabecalhoConteudo from "./CabecalhoConteudo";
import resumoTransacoesService from '@/services/resumoTransacoes';

export default {
  props: {
    despesas: Array,
    receitas: Array
  },
  components: {
    CabecalhoPrincipal,
    CabecalhoConteudo
  },
  computed: {
    totais() {
      return resumoTransacoesService.calcularTotais(this.despesas, this.receitas);
    }
  }
};
</script>

<style>
</style>

// React/src/componentes/cabecalho/Header/Header.js
import React from 'react';
import CabecalhoPrincipal from '../CabecalhoPrincipal/CabecalhoPrincipal';
import CabecalhoConteudo from '../CabecalhoConteudo/CabecalhoConteudo';
import resumoTransacoesService from 'services/resumoTransacoes';

const Header = (props) => {
  const totais = resumoTransacoesService.calcularTotais(props.despesas, props.receitas);
  return (
    <header id="cabecalho">
      <CabecalhoPrincipal saldo={totais.total}/>
      <CabecalhoConteudo totais={totais}/>
    </header>
  );
}

export default Header;
