// Angular/src/app/compartilhado/item-visao-geral/item-visao-geral.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-item-visao-geral',
  templateUrl: './item-visao-geral.component.html',
  styleUrls: ['./item-visao-geral.component.css']
})
export class ItemVisaoGeralComponent implements OnInit {
  @Input() item: any;
  constructor() { }

  ngOnInit() {
  }

}

<div class="visao-geral-container">
  <h5>
    <span class="ofuscado">{{item.descricao}}</span>
  </h5>
  <span class="texto-grande">{{item.valor | currency:'BRL'}}</span>
</div>

// React/src/componentes/compartilhado/ItemVisalGeral/ItemVisaoGeral.js
import React from 'react';
import formatacoesService from 'services/formatacoes';

const ItemVisaoGeral = (props) => {
  return (
    <div className="visao-geral-container">
      <h5><span className="ofuscado">{props.item.descricao}</span></h5>
      <span className="texto-grande">{formatacoesService.formatarMoeda(props.item.valor)}</span>
    </div>
  );
}

export default ItemVisaoGeral;
