// Vue/src/components/conteudo/receitas/Receitas.vue
<template>
  <section class="coluna-conteudo" id="receitas">
    <h3>Receitas</h3>
    <TabelaReceitas />
    <FormReceitas />
  </section>
</template>

<script>
import TabelaReceitas from './TabelaReceitas';
import FormReceitas from './FormReceitas';

export default {
  components: {
    TabelaReceitas,
    FormReceitas
  }
};
</script>

<style>
</style>

// React/src/componentes/conteudo/receitas/Receitas/Receitas.js
import React from 'react';
import TabelaReceitas from '../TabelaReceitas/TabelaReceitas';
import FormReceitas from '../FormReceitas/FormReceitas';

const Receitas = () => {
  return (
    <section className="coluna-conteudo" id="receitas">
      <h3>Receitas</h3>
      <TabelaReceitas />
      <FormReceitas />
    </section>
  );
}

export default Receitas;
