// Vue/src/components/cabecalho/Header.vue
<template>
  <header id="cabecalho">
    <CabecalhoPrincipal :saldo="totais.total"/>
    <CabecalhoConteudo :totais="totais"/>
  </header>
</template>

<script>
import CabecalhoPrincipal from "./CabecalhoPrincipal";
import CabecalhoConteudo from "./CabecalhoConteudo";
import resumoTransacoesService from '@/services/resumoTransacoes';

export default {
  props: {
    despesas: Array,
    receitas: Array
  },
  components: {
    CabecalhoPrincipal,
    CabecalhoConteudo
  },
  computed: {
    totais() {
      return resumoTransacoesService.calcularTotais(this.despesas, this.receitas);
    }
  }
};
</script>

<style>
</style>

// Angular/src/app/cabecalho/header/header.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ResumoTransacoesService } from 'src/app/services/resumo-transacoes.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  @Input() despesas: Array<any>;
  @Input() receitas: Array<any>;
  constructor(private resumoTransacoesService: ResumoTransacoesService) {
  }

  get totais() {
    if (!this.despesas || !this.receitas) {
      return null;
    }
    return this.resumoTransacoesService.calcularTotais(this.despesas, this.receitas);
  }

  ngOnInit() {
  }
}

<header id="cabecalho">
  <app-cabecalho-principal *ngIf="totais" [saldo]="totais.total"></app-cabecalho-principal>
  <app-cabecalho-conteudo *ngIf="totais" [totais]="totais"></app-cabecalho-conteudo>
</header>
