// React/src/componentes/compartilhado/ProgressoCategoria/ProgressoCategoria.js
import React from 'react';
import formatacoesService from 'services/formatacoes';

const ProgressoCategoria = (props) => {
  return (
    <div>
      <h5>
        <span className="ofuscado">{props.categoria.descricao} {formatacoesService.formatarMoeda(props.total)}</span>
      </h5>
      <progress value={props.total} max={props.categoria.previsto}></progress>
    </div>
  );
}

export default ProgressoCategoria;

// Angular/src/app/compartilhado/progresso-categoria/progresso-categoria.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-progresso-categoria',
  templateUrl: './progresso-categoria.component.html',
  styleUrls: ['./progresso-categoria.component.css']
})
export class ProgressoCategoriaComponent implements OnInit {
  @Input() categoria: any;
  @Input() total: number;
  constructor() { }

  ngOnInit() {
    console.log(this.total);
  }

}

<div>
  <h5>
    <span class="ofuscado">{{categoria.descricao}} {{total | currency:'BRL'}}</span>
  </h5>
  <progress [value]="total" [max]="categoria.previsto"></progress>
</div>
