// Vue/src/components/cabecalho/CabecalhoPrincipal.vue
<template>
  <section id="cabecalho-principal">
    <div id="container-esquerdo">
      <i class="fas fa-bars"></i>
    </div>
    <div id="container-central">
      <hgroup>
        <h5 class="ofuscado">Saldo atual</h5>
        <h2 id="saldo"></h2>
        <h4>
          <button class="btn btn-redondo">
            <i class="fas fa-caret-left"></i>
          </button>
          Maio
          <button class="btn btn-redondo">
            <i class="fas fa-caret-right"></i>
          </button>
        </h4>
      </hgroup>
    </div>
    <div id="container-direito">
      <i class="fas fa-cog"></i>
    </div>
  </section>
</template>

<script>
export default {};
</script>

<style>
</style>

// React/src/componentes/cabecalho/CabecalhoPrincipal/CabecalhoPrincipal.js
import React from 'react';

const CabecalhoPrincipal = () => {
  return (
    <section id="cabecalho-principal">
      <div id="container-esquerdo">
        <i className="fas fa-bars"></i>
      </div>
      <div id="container-central">
        <hgroup>
          <h5 className="ofuscado">Saldo atual</h5>
          <h2 id="saldo"></h2>
          <h4>
            <button className="btn btn-redondo">
              <i className="fas fa-caret-left"></i>
            </button>
            Maio
                            <button className="btn btn-redondo">
              <i className="fas fa-caret-right"></i>
            </button>
          </h4>
        </hgroup>
      </div>
      <div id="container-direito">
        <i className="fas fa-cog"></i>
      </div>
    </section>
  );
}

export default CabecalhoPrincipal;
