// Vue/src/components/compartilhado/GrupoTransacoes.vue
<template>
  <div class="grupo-container">
    <tr key="{props.grupo}">
      <td class="coluna-data" colspan="2">{{dataFormatada}}</td>
    </tr>
    <TransacaoGrupo
      v-for="transacao in transacoes"
      :key="grupo+transacao.descricao"
      :transacao="transacao"
      :obterCategoria="obterCategoria"
    />
  </div>
</template>

<script>
import formatacoesService from "@/services/formatacoes";
import TransacaoGrupo from "./TransacaoGrupo";

export default {
  components: {
    TransacaoGrupo
  },
  props: {
    grupo: String,
    transacoes: Array,
    obterCategoria: Function
  },
  computed: {
    dataFormatada() {
      return formatacoesService.formatarData(this.grupo);
    }
  }
};
</script>

<style scoped>

td {
  padding: 10px 0;
  border-bottom: 1px solid #ccc;
  color: #4b4b4d;
  font-weight: bold;
}

td.coluna-data {
  border: 0;
  padding-bottom: 0;
}
</style>

// React/src/componentes/compartilhado/GrupoTransacoes/GrupoTransacoes.js
import React from 'react';
import formatacoesService from 'services/formatacoes';

const GrupoTransacoes = (props) => {
  return [
    <tr key={props.grupo}>
      <td className="coluna-data" colSpan="2">{formatacoesService.formatarData(props.grupo)}</td>
    </tr>,
    props.transacoes.map(transacao => (
      <tr key={props.grupo+transacao.descricao}>
        <td className="coluna-descricao-transacao">
          {transacao.descricao}
          <p className="categoria-label">{props.obterCategoria(transacao)}</p>
        </td>
        <td className="coluna-valor-transacao">{formatacoesService.formatarMoeda(transacao.valor)}</td>
      </tr>
    ))
  ];
}

export default GrupoTransacoes;
