// Angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { DespesasService } from './services/despesas.service';
import { ReceitasService } from './services/receitas.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  despesas: Array<any>;
  receitas: Array<any>;
  constructor(private despesasService: DespesasService, private receitasService: ReceitasService) {
    this.listarDespesas();
    this.listarReceitas();
  }

  async listarDespesas() {
    this.despesas = await this.despesasService.listar();
  }

  async listarReceitas() {
    this.receitas = await this.receitasService.listar();
  }
}

<app-header
  [despesas]="despesas"
  [receitas]="receitas"></app-header>
<app-main
  [despesas]="despesas"
  (despesaAdicionada)="listarDespesas()"
  [receitas]="receitas"
  (receitaAdicionada)="listarReceitas()"></app-main>

// Vue/src/App.vue
<template>
  <div id="app">
    <Header
      :despesas="despesas"
      :receitas="receitas"/>
    <Main
      :despesas="despesas"
      @despesaAdicionada="listarDespesas()"
      :receitas="receitas"
      @receitaAdicionada="listarReceitas()"/>
  </div>
</template>

<script>
import "@fortawesome/fontawesome-free/css/all.css";
import "./font-montserrat.css";
import Header from "./components/cabecalho/Header";
import Main from "./components/conteudo/Main";
import despesasService from "@/services/despesas";
import receitasService from "@/services/receitas";

export default {
  name: "app",
  components: {
    Header,
    Main
  },
  data() {
    return {
      despesas: [],
      receitas: []
    };
  },
  created() {
    this.listarDespesas();
    this.listarReceitas();
  },
  methods: {
    async listarDespesas() {
      this.despesas = await despesasService.listar();
    },
    async listarReceitas() {
      this.receitas = await receitasService.listar();
    }
  }
};
</script>

<style src="./App.css"></style>
