// React/src/App.js
import React from 'react';
import './App.css';
import '@fortawesome/fontawesome-free/css/all.css';
import './font-montserrat.css';
import Header from './componentes/cabecalho/Header/Header';
import Main from './componentes/conteudo/Main/Main';

function App() {
  return (
    <div className="App">
      <Header />
      <Main />
    </div>
  );
}

export default App;

// Vue/src/App.vue
<template>
  <div id="app">
    <Header />
    <Main />
  </div>
</template>

<script>
import "@fortawesome/fontawesome-free/css/all.css";
import "./font-montserrat.css";
import Header from "./components/cabecalho/Header";
import Main from "./components/conteudo/Main";

export default {
  name: "app",
  components: {
    Header,
    Main
  }
};
</script>

<style src="./App.css"></style>
