// Vue/src/components/conteudo/despesas/TabelaDespesas.vue
<template>
  <table id="tabela-despesas" class="tabela-transacoes">
    <tbody>
      <GrupoTransacoes
        :grupo="grupo"
        :transacoes="transacoesGrupo(grupo)"
        :key="grupo"
        :obterCategoria="obterCategoria"
        v-for="grupo in datasOrdenadas"
      />
    </tbody>
  </table>
</template>

<script>
import GrupoTransacoes from "@/components/compartilhado/GrupoTransacoes";
import colecoesService from "@/services/colecoes";
import configuracoes from "@/services/configuracoes";

export default {
  components: {
    GrupoTransacoes
  },
  props: {
    despesas: Array
  },
  computed: {
    despesasAgrupadas() {
      return colecoesService.agrupar(this.despesas, "data");
    },
    datasOrdenadas() {
      return Object.keys(this.despesasAgrupadas).sort((a, b) => {
        if (new Date(b) < new Date(a)) {
          return -1;
        }
        if (new Date(b) > new Date(a)) {
          return 1;
        }
        return 0;
      });
    }
  },
  methods: {
    transacoesGrupo(grupo) {
      return this.despesasAgrupadas[grupo];
    },
    obterCategoria(despesa) {
      return configuracoes.categorias.find(
        categoria => categoria.identificador === despesa.categoria
      ).descricao;
    }
  }
};
</script>

<style>
</style>

// Angular/src/app/conteudo/despesas/tabela-despesas/tabela-despesas.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ColecoesService } from 'src/app/services/colecoes.service';
import { ConfiguracoesService } from 'src/app/services/configuracoes.service';

@Component({
  selector: 'app-tabela-despesas',
  templateUrl: './tabela-despesas.component.html',
  styleUrls: ['./tabela-despesas.component.css']
})
export class TabelaDespesasComponent implements OnInit {
  @Input() despesas: Array<any>;
  constructor(private colecoesService: ColecoesService, private configuracoes: ConfiguracoesService) {

  }

  ngOnInit() {
  }

  get despesasAgrupadas() {
    if (!this.despesas) {
      return [];
    }
    return this.colecoesService.agrupar(this.despesas, 'data');
  }

  get datasOrdenadas() {
    return Object.keys(this.despesasAgrupadas).sort((a, b) => {
      if (new Date(b) < new Date(a)) {
          return -1;
      }
      if (new Date(b) > new Date(a)) {
          return 1;
      }
      return 0;
    });
  }

  obterCategoria = (despesa: any) => {
    return this.configuracoes.categorias
      .find(categoria => categoria.identificador === despesa.categoria).descricao;
  }
}

<table id="tabela-despesas" class="tabela-transacoes">
  <tbody>
    <app-grupo-transacao *ngFor="let grupo of datasOrdenadas"
      [grupo]="grupo"
      [transacoes]="despesasAgrupadas[grupo]"
      [obterCategoria]="obterCategoria"></app-grupo-transacao>
  </tbody>
</table>
