// Angular/src/app/conteudo/receitas/form-receitas/form-receitas.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { ReceitasService } from 'src/app/services/receitas.service';

@Component({
  selector: 'app-form-receitas',
  templateUrl: './form-receitas.component.html',
  styleUrls: ['./form-receitas.component.css']
})
export class FormReceitasComponent implements OnInit {
  receita: any;
  @Output() receitaAdicionada = new EventEmitter();
  constructor(private receitasService: ReceitasService) {
    this.receita = {
      descricao: '',
      valor: 0,
      data: new Date(new Date().setHours(0, 0, 0, 0)).toISOString()
    };
  }

  ngOnInit() {
  }

  async onSubmit() {
    try {
      await this.receitasService.adicionar(this.receita);

      this.receita = {
        descricao: '',
        valor: 0,
        data: new Date(new Date().setHours(0, 0, 0, 0)).toISOString()
      };

      this.receitaAdicionada.emit();

      alert('Receita salva com sucesso');
    } catch {
      alert('Ocorreu um erro ao salvar a receita');
    }
  }
}

<section class="form-container" id="form-receita-container">
  <h4 class="titulo-form">Adicionar receita</h4>
  <form
    ngNativeValidate
    (ngSubmit)="onSubmit()"
    id="form-adicionar-receita"
    class="form"
    name="form-receita"
    action="#">
    <div class="linha-form">
      <label for="descricao">Descrição</label>
      <input
        type="text"
        [(ngModel)]="receita.descricao"
        name="descricao"
        required>
    </div>
    <div class="linha-form">
      <label for="valor">Valor</label>
      <input
        type="number"
        name="valor"
        [(ngModel)]="receita.valor"
        step="0.01"
        required>
    </div>
    <div class="linha-form">
      <button class="btn" type="submit">Adicionar</button>
    </div>
  </form>
</section>

// Vue/src/components/conteudo/receitas/FormReceitas.vue
<template>
  <section class="form-container" id="form-receita-container">
    <h4 class="titulo-form">Adicionar receita</h4>
    <form
      @submit="submit"
      id="form-adicionar-receita"
      class="form"
      name="form-receita"
      action="#">
      <div class="linha-form">
        <label for="descricao">Descrição</label>
        <input
          type="text"
          v-model="receita.descricao"
          name="descricao"
          required />
      </div>
      <div class="linha-form">
        <label for="valor">Valor</label>
        <input
          type="number"
          name="valor"
          v-model="receita.valor"
          step="0.01"
          required />
      </div>
      <div class="linha-form">
        <button class="btn" type="submit">Adicionar</button>
      </div>
    </form>
  </section>
</template>

<script>
import receitasService from '@/services/receitas';

export default {
  data() {
    return {
      receita: {
        descricao: '',
        valor: 0,
        data: new Date(new Date().setHours(0,0,0,0)).toISOString()
      }
    }
  },
  methods: {
    async submit(e) {
      e.preventDefault();
      try {
        await receitasService.adicionar(this.receita);

        this.receita = {
          descricao: '',
          valor: 0,
          data: new Date(new Date().setHours(0,0,0,0)).toISOString()
        };

        this.$emit('receitaAdicionada');

        alert('Receita salva com sucesso');
      } catch {
        alert('Ocorreu um erro ao salvar a receita');
      }
    }
  }
};
</script>

<style>
</style>
