// React/src/componentes/conteudo/receitas/FormReceitas/FormReceitas.js
import React from 'react';

const FormReceitas = () => {
  return (
    <section className="form-container" id="form-receita-container">
      <h4 className="titulo-form">Adicionar receita</h4>
      <form id="form-adicionar-receita" className="form" name="form-receita" action="#">
        <div className="linha-form">
          <label htmlFor="descricao">Descrição</label>
          <input type="text" id="descricao" name="descricao" required />
        </div>
        <div className="linha-form">
          <label htmlFor="valor">Valor</label>
          <input type="number" name="valor" id="valor" step="0.01" required />
        </div>
        <div className="linha-form">
          <button className="btn" type="submit">Adicionar</button>
        </div>
      </form>
    </section>
  );
}

export default FormReceitas;

// Vue/src/components/conteudo/receitas/FormReceitas.vue
<template>
  <section class="form-container" id="form-receita-container">
    <h4 class="titulo-form">Adicionar receita</h4>
    <form id="form-adicionar-receita" class="form" name="form-receita" action="#">
      <div class="linha-form">
        <label for="descricao">Descrição</label>
        <input type="text" id="descricao" name="descricao" required />
      </div>
      <div class="linha-form">
        <label for="valor">Valor</label>
        <input type="number" name="valor" id="valor" step="0.01" required />
      </div>
      <div class="linha-form">
        <button class="btn" type="submit">Adicionar</button>
      </div>
    </form>
  </section>
</template>

<script>
export default {};
</script>

<style>
</style>
