// React/src/componentes/conteudo/receitas/TabelaReceitas/TabelaReceitas.js
import React from 'react';
import colecoesService from 'services/colecoes';
import GrupoTransacoes from 'componentes/compartilhado/GrupoTransacoes/GrupoTransacoes';

const agruparReceitas = receitas => colecoesService.agrupar(receitas, 'data');

const obterDatasOrdenadas = receitasAgrupadas => {
  return Object.keys(receitasAgrupadas)
    .sort((a, b) => {
      if (new Date(b) < new Date(a)) {
          return -1;
      }
      if (new Date(b) > new Date(a)) {
          return 1;
      }
      return 0;
  });
}

const TabelaReceitas = (props) => {
  const receitasAgrupadas = agruparReceitas(props.receitas);
  return (
    <table id="tabela-receitas" className="tabela-transacoes">
      <tbody>
        {
          obterDatasOrdenadas(receitasAgrupadas).map(grupo => (
            <GrupoTransacoes
              key={grupo}
              grupo={grupo}
              transacoes={receitasAgrupadas[grupo]}
              obterCategoria={() => 'Receitas'}/>
          ))
        }
      </tbody>
    </table>
  );
}

export default TabelaReceitas;

// Vue/src/components/conteudo/receitas/TabelaReceitas.vue
<template>
  <table id="tabela-receitas" class="tabela-transacoes">
    <tbody>
      <GrupoTransacoes
        :grupo="grupo"
        :transacoes="transacoesGrupo(grupo)"
        :key="grupo"
        :obterCategoria="() => 'Receitas'"
        v-for="grupo in datasOrdenadas"
      />
    </tbody>
  </table>
</template>

<script>
import GrupoTransacoes from "@/components/compartilhado/transacoes/GrupoTransacoes";
import colecoesService from "@/services/colecoes";

export default {
  components: {
    GrupoTransacoes
  },
  props: {
    receitas: Array
  },
  computed: {
    receitasAgrupadas() {
      return colecoesService.agrupar(this.receitas, "data");
    },
    datasOrdenadas() {
      return Object.keys(this.receitasAgrupadas).sort((a, b) => {
        if (new Date(b) < new Date(a)) {
          return -1;
        }
        if (new Date(b) > new Date(a)) {
          return 1;
        }
        return 0;
      });
    }
  },
  methods: {
    transacoesGrupo(grupo) {
      return this.receitasAgrupadas[grupo];
    }
  }
};
</script>

<style>
</style>
