// Vue/src/components/conteudo/despesas/Despesas.vue
<template>
  <section class="coluna-conteudo" id="despesas">
    <h3>Despesas</h3>
    <TabelaDespesas />
    <FormDespesas />
  </section>
</template>

<script>
import TabelaDespesas from './TabelaDespesas';
import FormDespesas from './FormDespesas';

export default {
  components: {
    TabelaDespesas,
    FormDespesas
  }
};
</script>

<style>
</style>

// React/src/componentes/conteudo/despesas/Despesas/Despesas.js
import React from 'react';
import TabelaDespesas from '../TabelaDespesas/TabelaDespesas';
import FormDespesas from '../FormDespesas/FormDespesas';

const Despesas = () => {
  return (
    <section className="coluna-conteudo" id="despesas">
      <h3>Despesas</h3>
      <TabelaDespesas />
      <FormDespesas />
    </section>
  );
}

export default Despesas;
