// React/src/componentes/compartilhado/ItemVisalGeral/ItemVisaoGeral.js
import React from 'react';
import formatacoesService from 'services/formatacoes';

const ItemVisaoGeral = (props) => {
  return (
    <div className="visao-geral-container">
      <h5><span className="ofuscado">{props.item.descricao}</span></h5>
      <span className="texto-grande">{formatacoesService.formatarMoeda(props.item.valor)}</span>
    </div>
  );
}

export default ItemVisaoGeral;

// Vue/src/components/compartilhado/resumo/ItemVisaoGeral.vue
<template>
  <div class="visao-geral-container">
    <h5>
      <span class="ofuscado">{{item.descricao}}</span>
    </h5>
    <span class="texto-grande">{{valorFormatado}}</span>
  </div>
</template>

<script>
import formatacoesService from '@/services/formatacoes';

export default {
  props: {
    item: Object
  },
  computed: {
    valorFormatado() {
      return formatacoesService.formatarMoeda(this.item.valor);
    }
  }
};
</script>

<style>
</style>
