// React/src/componentes/compartilhado/ProgressoCategoria/ProgressoCategoria.js
import React from 'react';
import formatacoesService from 'services/formatacoes';

const ProgressoCategoria = (props) => {
  return (
    <div>
      <h5>
        <span className="ofuscado">{props.categoria.descricao} {formatacoesService.formatarMoeda(props.total)}</span>
      </h5>
      <progress value={props.total} max={props.categoria.previsto}></progress>
    </div>
  );
}

export default ProgressoCategoria;

// Vue/src/components/compartilhado/resumo/ProgressoCategoria.vue
<template>
  <div>
    <h5>
      <span
        class="ofuscado"
      >{{categoria.descricao}} {{totalFormatado}}</span>
    </h5>
    <progress :value="total" :max="categoria.previsto"></progress>
  </div>
</template>

<script>
import formatacoesService from '@/services/formatacoes';

export default {
  props: {
    categoria: Object,
    total: Number
  },
  computed: {
    totalFormatado() {
      return formatacoesService.formatarMoeda(this.total);
    }
  }
};
</script>

<style>
</style>
