// Vue/src/components/conteudo/receitas/TabelaReceitas.vue
<template>
  <table id="tabela-receitas" class="tabela-transacoes">
    <tbody>
      <GrupoTransacoes
        :grupo="grupo"
        :transacoes="transacoesGrupo(grupo)"
        :key="grupo"
        :obterCategoria="() => 'Receitas'"
        v-for="grupo in datasOrdenadas"
      />
    </tbody>
  </table>
</template>

<script>
import GrupoTransacoes from "@/components/compartilhado/transacoes/GrupoTransacoes";
import colecoesService from "@/services/colecoes";

export default {
  components: {
    GrupoTransacoes
  },
  props: {
    receitas: Array
  },
  computed: {
    receitasAgrupadas() {
      return colecoesService.agrupar(this.receitas, "data");
    },
    datasOrdenadas() {
      return Object.keys(this.receitasAgrupadas).sort((a, b) => {
        if (new Date(b) < new Date(a)) {
          return -1;
        }
        if (new Date(b) > new Date(a)) {
          return 1;
        }
        return 0;
      });
    }
  },
  methods: {
    transacoesGrupo(grupo) {
      return this.receitasAgrupadas[grupo];
    }
  }
};
</script>

<style>
</style>

// Angular/src/app/conteudo/receitas/tabela-receitas/tabela-receitas.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ColecoesService } from 'src/app/services/colecoes.service';

@Component({
  selector: 'app-tabela-receitas',
  templateUrl: './tabela-receitas.component.html',
  styleUrls: ['./tabela-receitas.component.css']
})
export class TabelaReceitasComponent implements OnInit {
  @Input() receitas: Array<any>;
  constructor(private colecoesService: ColecoesService) { }

  ngOnInit() {
  }

  get receitasAgrupadas() {
    if (!this.receitas) {
      return [];
    }
    return this.colecoesService.agrupar(this.receitas, 'data');
  }

  get datasOrdenadas() {
    return Object.keys(this.receitasAgrupadas).sort((a, b) => {
      if (new Date(b) < new Date(a)) {
          return -1;
      }
      if (new Date(b) > new Date(a)) {
          return 1;
      }
      return 0;
    });
  }

  obterCategoria(): string {
    return 'Receitas';
  }
}

<table id="tabela-receitas" class="tabela-transacoes">
  <tbody>
    <app-grupo-transacao *ngFor="let grupo of datasOrdenadas"
      [grupo]="grupo"
      [transacoes]="receitasAgrupadas[grupo]"
      [obterCategoria]="obterCategoria"></app-grupo-transacao>
  </tbody>
</table>
