// Angular/src/app/cabecalho/cabecalho-conteudo/cabecalho-conteudo.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { ConfiguracoesService } from 'src/app/services/configuracoes.service';

@Component({
  selector: 'app-cabecalho-conteudo',
  templateUrl: './cabecalho-conteudo.component.html',
  styleUrls: ['./cabecalho-conteudo.component.css']
})
export class CabecalhoConteudoComponent implements OnInit {
  @Input() totais: any;
  constructor(private configuracoes: ConfiguracoesService) { }

  ngOnInit() {
  }

  get categoriaReceitas() {
    return {
      identificador: 'receitas',
      descricao: 'Receitas',
      previsto: this.configuracoes.previstoDeReceita
    };
  }

  get categoriaDespesas() {
    const previstoDespesas = this.configuracoes.categorias.reduce(
      (acumulador, categoria) => {
        acumulador += categoria.previsto;
        return acumulador;
      },
      0
    );

    return {
      identificador: 'despesas',
      descricao: 'Despesas',
      previsto: previstoDespesas
    };
  }

  get categorias() {
    return this.configuracoes.categorias;
  }

  totalPorCategoria(categoria: any) {
    return this.totais[categoria.identificador] || 0;
  }
}

<section id="cabecalho-conteudo">
  <div *ngIf="totais" id="progresso-principal">
    <app-progresso-categoria [categoria]="categoriaReceitas" [total]="totais[categoriaReceitas.identificador]">
    </app-progresso-categoria>
    <app-progresso-categoria [categoria]="categoriaDespesas" [total]="totais[categoriaDespesas.identificador]">
    </app-progresso-categoria>
  </div>
  <div *ngIf="categorias" id="progresso-categoria">
    <app-progresso-categoria *ngFor="let categoria of categorias" [categoria]="categoria"
      [total]="totalPorCategoria(categoria)"></app-progresso-categoria>
  </div>
  <div id="visao-geral">
    <app-item-visao-geral [item]="{ descricao: 'Receitas', valor: totais.receitas }"></app-item-visao-geral>
    <app-item-visao-geral [item]="{ descricao: 'Despesas', valor: totais.despesas }"></app-item-visao-geral>
    <app-item-visao-geral [item]="{ descricao: 'Economia', valor: totais.total }"></app-item-visao-geral>
  </div>
</section>

// Vue/src/components/cabecalho/CabecalhoConteudo.vue
<template>
  <section id="cabecalho-conteudo">
    <div id="progresso-principal">
      <ProgressoCategoria
        :categoria="categoriaReceitas"
        :total="totais[categoriaReceitas.identificador]"
      />
      <ProgressoCategoria
        :categoria="categoriaDespesas"
        :total="totais[categoriaDespesas.identificador]"
      />
    </div>
    <div id="progresso-categoria">
      <ProgressoCategoria
        v-for="categoria in categorias"
        :key="categoria.identificador"
        :categoria="categoria"
        :total="totais[categoria.identificador] || 0"
      />
    </div>
    <div id="visao-geral">
      <ItemVisaoGeral :item="{ descricao: 'Receitas', valor: totais.receitas }" />
      <ItemVisaoGeral :item="{ descricao: 'Despesas', valor: totais.despesas }" />
      <ItemVisaoGeral :item="{ descricao: 'Economia', valor: totais.total }" />
    </div>
  </section>
</template>

<script>
import configuracoes from "@/services/configuracoes";
import ProgressoCategoria from "@/components/compartilhado/resumo/ProgressoCategoria";
import ItemVisaoGeral from "@/components/compartilhado/resumo/ItemVisaoGeral";

export default {
  components: {
    ProgressoCategoria,
    ItemVisaoGeral
  },
  props: {
    totais: Object
  },
  computed: {
    categoriaReceitas() {
      return {
        descricao: "Receitas",
        identificador: "receitas",
        previsto: configuracoes.previstoDeReceita
      };
    },
    categoriaDespesas() {
      const previstoDespesas = configuracoes.categorias.reduce(
        (acumulador, categoria) => {
          acumulador += categoria.previsto;
          return acumulador;
        },
        0
      );

      return {
        descricao: "Despesas",
        identificador: "despesas",
        previsto: previstoDespesas
      };
    },
    categorias() {
      return configuracoes.categorias;
    }
  }
};
</script>

<style>
</style>
