// Angular/src/app/cabecalho/cabecalho-principal/cabecalho-principal.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-cabecalho-principal',
  templateUrl: './cabecalho-principal.component.html',
  styleUrls: ['./cabecalho-principal.component.css']
})
export class CabecalhoPrincipalComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<section id="cabecalho-principal">
    <div id="container-esquerdo">
        <i class="fas fa-bars"></i>
    </div>
    <div id="container-central">
        <h5 class="ofuscado">Saldo atual</h5>
        <h2 id="saldo"></h2>
        <h4>
            <button class="btn btn-redondo">
                <i class="fas fa-caret-left"></i>
            </button>
            Maio
            <button class="btn btn-redondo">
                <i class="fas fa-caret-right"></i>
            </button>
        </h4>
    </div>
    <div id="container-direito">
        <i class="fas fa-cog"></i>
    </div>
</section>

// Vue/src/components/cabecalho/CabecalhoPrincipal.vue
<template>
  <section id="cabecalho-principal">
    <div id="container-esquerdo">
      <i class="fas fa-bars"></i>
    </div>
    <div id="container-central">
      <hgroup>
        <h5 class="ofuscado">Saldo atual</h5>
        <h2 id="saldo"></h2>
        <h4>
          <button class="btn btn-redondo">
            <i class="fas fa-caret-left"></i>
          </button>
          Maio
          <button class="btn btn-redondo">
            <i class="fas fa-caret-right"></i>
          </button>
        </h4>
      </hgroup>
    </div>
    <div id="container-direito">
      <i class="fas fa-cog"></i>
    </div>
  </section>
</template>

<script>
export default {};
</script>

<style>
</style>
